language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --no-deps
after_success:
  - travis-cargo --only nightly doc-upload
env:
  global:
    secure: "O7ROybO/Wl/4rlizucX6Q+vivjX8M07TAfzopRSd3LfsigxXcwsRINlcq57s1LWvKXY4qtQTb16V7qsuMrz0sqSyUdoz7X96M5YjIQUtqgiQHGpCRD0+1vD9sthmo4iDQ3Tn1hMNeMOPSQ4mS4ozsfNHWnLCttV0a/6iUP+u6Dw="



notifications:
  email:
    on_success: never
