language: rust

cache:
  cargo: true
before_cache:
  - find ./target/debug -maxdepth 1 -type f -delete
  - rm -f  ./target/.rustc_info.json

env:
  global:
    - CARGO_INCREMENTAL=0
    - RUSTFLAGS="-C debuginfo=0"

rust:
  - stable
  - beta
  - nightly

before_install:
  - script/ci/cargo-clean-on-new-rustc-version.sh
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt -- --check
  - cargo clippy --all-targets --all-features --all
  - cargo test

notifications:
  email:
    on_success: never
