[package]

name = "conduit-router"
version = "0.5.0"
authors = ["wycats@gmail.com"]

[[lib]]

name = "conduit-router"

[dependencies.conduit]

git = "https://github.com/conduit-rust/conduit.git"

[dependencies.route-recognizer]

git = "https://github.com/conduit-rust/route-recognizer.rs.git"
