[package]

name = "conduit-test"
version = "0.9.0-alpha.2"
authors = ["wycats@gmail.com",
           "Alex Crichton <alex@alexcrichton.com>"]
description = "Testing utilities for conduit-based stacks"
repository = "https://github.com/conduit-rust/conduit-test"
license = "MIT"

[dependencies]
conduit = { git = "https://github.com/jtgeibel/conduit", rev = "0deff5b" } # "0.9.0-alpha.2"
