[project]

name = "crates.io"
authors = ["alex@alexcrichton.com"]
version = "0.1.0"

[[bin]]

name = "main"

[dependencies.civet]

git = "git://github.com/wycats/rust-civet"

[dependencies.route-recognizer]

git = "git://github.com/wycats/route-recognizer.rs"

[dependencies.postgres]

git = "git://github.com/alexcrichton/rust-postgres"
branch = "cargo"

[dependencies.phf]

git = "git://github.com/alexcrichton/rust-phf"
branch = "cargo"
