[package]

name = "conduit-static"
version = "0.6.1"
authors = ["wycats@gmail.com",
           "Alex Crichton <alex@alexcrichton.com>"]
description = "Middleware for serving static files for conduit"
repository = "https://github.com/conduit-rust/conduit-static"
license = "MIT"

[dependencies]
conduit = "0.6"
conduit-mime-types = "0.6"
time = "0.1.0"

[dev-dependencies]
civet = "0.1.0"
conduit-test = "0.6"
