[package]

name = "conduit-middleware"
version = "0.6.2"
authors = ["wycats@gmail.com",
           "Alex Crichton <alex@alexcrichton.com>"]
description = "HTTP Middleware interface using the conduit interface"
repository = "https://github.com/conduit-rust/conduit-middleware"
license = "MIT"

[dependencies]
conduit = "0.6"
semver = "0.1"
