[package]
name = "conduit-hyper"
version = "0.1.0"
authors = ["Justin Geibel <jtgeibel@gmail.com>"]
license = "MIT"
description = "Use hyper as the server for a conduit stack"
repository = "https://github.com/jtgeibel/conduit-hyper"

[dependencies]
conduit = "0.8"
futures = "0.1"
hyper = { git = "https://github.com/hyperium/hyper" }
http = "0.1"
semver = "0.5" # Must match version in conduit for now
