[package]

name = "conduit-router"
version = "0.5.4"
authors = ["wycats@gmail.com"]
license = "MIT"
description = "Router middleware for conduit based on route-recognizer"
repository = "https://github.com/conduit-rust/conduit-router"

[dependencies]
conduit = "0.5.0"
route-recognizer = "0.1.0"
