[project]

name = "crates.io"
authors = ["alex@alexcrichton.com"]
version = "0.1.0"

[[bin]]

name = "main"

[dependencies.civet]

git = "https://github.com/wycats/rust-civet"

[dependencies.conduit-router]

git = "https://github.com/conduit-rust/conduit-router"

[dependencies.conduit-middleware]

git = "https://github.com/conduit-rust/conduit-middleware"

[dependencies.rust-postgres]

git = "https://github.com/sfackler/rust-postgres"

[dependencies.html]

path = "src/html"
