[workspace]
members = [
    "conduit",
    "conduit-middleware",
    "conduit-router",
    "conduit-test",
    "example",
]

[patch.crates-io]
# we override the `conduit` package path here until we have imported the
# `civet` crate into this repository. `civet` is needed by the examples, but
# has a dependency on `conduit`.
conduit = { path = "conduit" }
