[package]

name = "conduit-static"
version = "0.5.0"
authors = ["wycats@gmail.com"]

[dev-dependencies.civet]
git = "https://github.com/wycats/rust-civet.git"

[dependencies.conduit]
git = "https://github.com/conduit-rust/conduit.git"

[dependencies.mime-types]
git = "https://github.com/conduit-rust/mime-types.git"

[dependencies.time]
git = "https://github.com/rust-lang/time"

[dev-dependencies.conduit-test]
git = "https://github.com/conduit-rust/conduit-test.git"
