[package]
name = "conduit-hyper"
version = "0.2.0-a.0"
authors = ["Justin Geibel <jtgeibel@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Host a conduit based web application on a hyper server"
repository = "https://github.com/jtgeibel/conduit-hyper"
readme = "README.md"
edition = "2018"

[dependencies]
conduit = "0.8"
futures = "0.1"
hyper = "0.12"
http = "0.1"
log = "0.4"
semver = "0.5" # Must match version in conduit for now
tokio-threadpool = "0.1.12"

[dev-dependencies]
conduit = "0.8"
conduit-router = "0.8"
tokio = "0.1"
