[package]

name = "conduit-conditional-get"
version = "0.9.0-alpha.2"
authors = ["wycats@gmail.com",
           "Alex Crichton <alex@alexcrichton.com>"]
license = "MIT"
description = """
Middleware to transform GET into a conditional response if headers indicate that
the response is fresh.
"""

[dependencies]
conduit = { git = "https://github.com/jtgeibel/conduit", rev = "0deff5b" } # "0.9.0-alpha.2"
conduit-middleware ={ git = "https://github.com/jtgeibel/conduit-middleware", rev = "0f3aa38" } # "0.9.0-alpha.2"
time = "0.1.0"

[dev-dependencies]
conduit-test =  { git = "https://github.com/jtgeibel/conduit-test", rev = "b71595f" } # "0.9.0-alpha.2"
