[package]
name = "conduit-hyper"
version = "0.2.0-alpha.2"
authors = ["Justin Geibel <jtgeibel@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Host a conduit based web application on a hyper server"
repository = "https://github.com/jtgeibel/conduit-hyper"
readme = "README.md"
edition = "2018"

[dependencies]
conduit = "0.8"
futures = "0.3"
hyper = "0.13"
http = "0.2"
tracing = { version = "0.1", features = ["log"] }
semver = "0.5" # Must match version in conduit for now
tokio = { version = "0.2", features = ["blocking", "rt-threaded"] }
tower-service = "0.3"

[dev-dependencies]
conduit-router = "0.8"
env_logger = "0.7"
tokio = { version = "0.2", features = ["macros"] }
