[package]

name = "conduit-test"
version = "0.7.3"
authors = ["wycats@gmail.com",
           "Alex Crichton <alex@alexcrichton.com>"]
description = "Testing utilities for conduit-based stacks"
repository = "https://github.com/conduit-rust/conduit-test"
license = "MIT"

[dependencies]
conduit = "0.7"
semver = "0.2"
