[package]

name = "s3"
version = "0.0.1"
authors = []

[[lib]]

name = "s3"
path = "lib.rs"

[dependencies.curl]
git = "https://github.com/alexcrichton/curl-rust"
branch = "build-cmd"

[dependencies.openssl]
git = "https://github.com/sfackler/rust-openssl"
