[package]
name = "crates_io_smoke_test"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[dependencies]
anyhow = "=1.0.72"
clap = { version = "=4.3.19", features = ["derive", "env", "unicode", "wrap_help"] }
secrecy = "=0.8.0"
tempfile = "=3.7.0"
tracing = "=0.1.37"
tracing-subscriber = { version = "=0.3.17", features = ["env-filter"] }
