[package]
name = "crates_io_cdn_logs"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
chrono = { version = "=0.4.33", features = ["serde"] }
semver = "=1.0.21"

[dev-dependencies]
insta = "=1.34.0"
