name: CI / Backend

on:
  push:
    branches:
      - main
      - master

  pull_request:

env:
  DIESEL_CLI_VERSION: 1.4.1
  RUST_VERSION: 1.65.0

jobs:
  lint:
    runs-on: ubuntu-20.04

    env:
      RUSTFLAGS: "-D warnings"

    steps:
      - uses: actions/checkout@v3.1.0

      - run: rustup default ${{ env.RUST_VERSION }}
      - run: rustup component add rustfmt
      - run: rustup component add clippy

      - uses: Swatinem/rust-cache@v2.2.0

      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features --all

  test:
    runs-on: ubuntu-20.04

    env:
      RUST_BACKTRACE: 1
      DATABASE_URL: postgres://postgres:postgres@localhost/cargo_registry_test
      TEST_DATABASE_URL: postgres://postgres:postgres@localhost/cargo_registry_test
      RUSTFLAGS: "-D warnings"
      MALLOC_CONF: "background_thread:true,abort_conf:true,abort:true,junk:true"

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3.1.0

      - run: rustup default ${{ env.RUST_VERSION }}

      - uses: Swatinem/rust-cache@v2.2.0

      - run: cargo install diesel_cli --vers ${{ env.DIESEL_CLI_VERSION }} --no-default-features --features postgres --debug
      - run: diesel database setup --locked-schema

      - run: cargo test --workspace
