name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 3 * * 0' # weekly, Sunday at 3am

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Cache cargo registry and git deps
        uses: actions/cache@main
        with:
          path: |
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
          key: ${{ runner.os }}-cargo-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache cargo build
        uses: actions/cache@main
        with:
          path: target
          key: ${{ runner.os }}-lint-target-${{ steps.rustc.outputs.version }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-lint-target-${{ steps.rustc.outputs.version }}-

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
            command: fmt
            args: --all -- --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  tests:
    strategy:
      matrix:
        rust: [stable, beta, nightly]

    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Cache cargo registry and git deps
        uses: actions/cache@main
        with:
          path: |
            ~/.cargo/registry/cache
            ~/.cargo/registry/index
          key: ${{ runner.os }}-cargo-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Cache cargo build
        uses: actions/cache@main
        with:
          path: target
          key: ${{ runner.os }}-target-${{ steps.rustc.outputs.version }}-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-target-${{ steps.rustc.outputs.version }}-

      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
