name: CI

on:
  push:
  pull_request:

env:
  # minimum supported rust version
  MSRV: 1.46.0

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-18.04

    env:
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: "-C debuginfo=0 -D warnings"

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust v${{ env.MSRV }}
        run: |
          rustup default ${{ env.MSRV }}

      - name: Install lint tools
        run: |
          rustup component add rustfmt
          rustup component add clippy

      - uses: Swatinem/rust-cache@v1.3.0

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy --all-targets --all-features --all

      - name: Test
        run: cargo test
